### ISSUE TITLE
Compatibility Magento 2.1 / 2.2

### ISSUE THREAD

**Issue by avstudnitz** [Sebwite/Magento2-Product-Downloads#6]
There is a branch https://github.com/studioemma/Magento2-Product-Downloads/tree/2.1-dev-store-scope which is fully compatible to Magento 2.1 and 2.2, I just tested it on 2.2.2 OpenSource. Could you merge that and tag a new release?
Thanks a lot for your module!

**Comment by XigenDominic** [comment]
I've just installed this on a 2.2.2 store but don't see the download tab on a simple product?  Using a vanilla store with Magento sample data.  Or do I misunderstand how this should work?

**Comment by avstudnitz** [comment]
@XigenDominic No, it does exactly that. Works fine on my 2.2.3 installation.

**Comment by XigenDominic** [comment]
Yes - confirmed showing on 2.2.3 install (although this doesn't have sample data).  Thanks!

**Comment by thiagosantos** [comment]
Will @avstudnitz fork be merged?

**Comment by SilvanLaroo** [comment]
We've just released a new version that supports Magento 2.1 and Magento 2.2.
